version: "3.8"
services:
    db_dev:
        image: postgres
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
    api:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        restart: always
        environment:
            - POSTGRES_HOST=db_dev
            - POSTGRES_DB=maas_dev
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        depends_on:
            - db_dev
